### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [DiplomarbeitSensorstation/Sensorstation#1]
In the file "Sensorstation/Arduino/LibraryI2CSensors/LibraryI2CSensors.ino" the functions to write data and read data via the I2C bus are mixed.
See my [alternative explanation](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library) of the functions of the Wire library.

**Comment by DiplomarbeitSensorstation** [comment]
Hello, sorry for the late reply!
I rewrote everything onto a single ESP32 device and added some features. 
Currently everything seems to be working fine. 
If there is still a problem with mixed read and write could you please further elaborate that,
I didn't quite catch that.
Thank you!

**Comment by Koepel** [comment]
The usage of the Wire library in OneMicrocontroller.ino is okay.
